In [81]:
import pandas as pd
import numpy as np

## Q1. Pandas version

What version of Pandas did you install?

In [82]:
pd.__version__

'3.0.6'

## Getting Data

In [83]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-23 21:42:28--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.02s

2026-09-23 21:42:28 (31.3 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [84]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q2. Records count
How many records are in the dataset?

In [85]:
df.shape

(10000, 11)

## Q3. Fuel types
How many fuel types are presented in the dataset?

In [86]:
df['fuel_type'].nunique()

3

## Q4. Missing values
How many columns in the dataset have missing values?

In [87]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [88]:
df.where(df['origin'] == 'Asia').fuel_efficiency_mpg.max()

np.float64(41.2)

## Q6. Median value of horsepower
Find the median value of the horsepower column in the dataset.

Next, calculate the most frequent value of the same horsepower column.

Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

Now, calculate the median value of horsepower once again.

Has it changed?

In [89]:
df['horsepower'].median()

np.float64(254.0)

In [90]:
unique_values, counts = np.unique(df['horsepower'],return_counts = True)
print(unique_values, counts)
index_max_freq_value = np.argmax(counts)
unique_values[index_max_freq_value]

[171. 174. 175. 178. 181. 182. 184. 186. 187. 188. 190. 191. 192. 193.
 194. 195. 196. 197. 198. 199. 200. 201. 202. 203. 204. 205. 206. 207.
 208. 209. 210. 211. 212. 213. 214. 215. 216. 217. 218. 219. 220. 221.
 222. 223. 224. 225. 226. 227. 228. 229. 230. 231. 232. 233. 234. 235.
 236. 237. 238. 239. 240. 241. 242. 243. 244. 245. 246. 247. 248. 249.
 250. 251. 252. 253. 254. 255. 256. 257. 258. 259. 260. 261. 262. 263.
 264. 265. 266. 267. 268. 269. 270. 271. 272. 273. 274. 275. 276. 277.
 278. 279. 280. 281. 282. 283. 284. 285. 286. 287. 288. 289. 290. 291.
 292. 293. 294. 295. 296. 297. 298. 299. 300. 301. 302. 303. 304. 305.
 306. 307. 308. 309. 310. 311. 312. 313. 314. 315. 316. 317. 318. 319.
 320. 321. 322. 323. 324. 325. 326. 327. 328. 329. 330. 332. 334.  nan] [  1   1   1   1   4   2   2   1   4   2   4   4   2   1   2   5   3   6
   6   6  11  18  15   9  12  15  22  21  24  24  26  25  39  33  30  34
  41  32  37  43  50  54  48  65  64  57  85  74  83  85  95  91  91 109
 111 129 131  99 127 126 147 127 129 146 160 137 168 133 139 160 162 159
 174 165 155 157 168 137 160 165 142 141 137 140 136 133 147 140 148 143
 128 120 104 124 100  98 112  96  94 113  88  74  90  77  76  47  70  68
  62  40  44  39  31  26  35  34  33  34  21  18  31  15  18  12  19  13
  12  12   8   6   9   5   7   8   8   4   2   2   8   3   1   4   1   2
   3   3   2   1   1   3   1   3   2 877]

np.float64(nan)

In [91]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [92]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [93]:
df['horsepower'].median()

np.float64(252.0)

## Q7. Sum of weights

**Select all the cars from Asia**

In [94]:
df.loc[df['origin'] == 'Asia']

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

**Select only columns vehicle_weight and model_year**

In [95]:
df[['vehicle_weight','model_year']].loc[df['origin'] == 'Asia']

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

**Select the first 7 values**

In [96]:
df[['vehicle_weight','model_year']].loc[df['origin'] == 'Asia'].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

**Get the underlying NumPy array. Let's call it X.**

In [97]:
x = df[['vehicle_weight','model_year']].loc[df['origin'] == 'Asia'].head(7).values

**Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.**

In [98]:
xtx = x.T.dot(x)

**Invert XTX.**

In [99]:
xtx_inverse = np.linalg.inv(xtx)

**Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].**

In [100]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

**Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.**

In [101]:
print(xtx_inverse.shape,x.T.shape,y.shape)
w = xtx_inverse.dot(x.T).dot(y)

(2, 2) (2, 7) (7,)

**What's the sum of all the elements of the result?**

In [102]:
w.sum()

np.float64(0.36919696904925486)